services:
  blue:
    build: .
    image: api:local
    environment:
      ENVIRONMENT: blue
      FORCE_UNHEALTHY: ${BLUE_UNHEALTHY:-false}
    ports:
      - "8001:8000"

  green:
    build: .
    image: api:local
    environment:
      ENVIRONMENT: green
      FORCE_UNHEALTHY: ${GREEN_UNHEALTHY:-false}
    ports:
      - "8002:8000"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - blue
      - green
